### PR TITLE
Create italian.json

### PR DESCRIPTION
**Pull request by kz-n**
Notes:
As said in the discord, I'm not sure what Player Entitlements are, I've decided to take a literal translation approach, which means "Player Rights" in Italian

### CODE REVIEW

**Comment by Matix-Media** [comment]
Except for the name everything seems to look good. Please check my comment in the name

**Comment by kz-n** [comment]
I don't seem to see a comment in the name, what's wrong with it?

**Comment by Hanro50** [comment]
Passed inspection. Sorry it took this long.

**Pull request merged**
