### PR TITLE
Small fixes on the english translation

### PR DESCRIPTION
**Pull request by kz-n**

### CODE REVIEW

**Comment by Matix-Media** [comment]
Are you sure that the law in south Korean law should be uppercase?

**Comment by Hanro50** [comment]
South Korea is the name of a country?

**Comment by Matix-Media** [comment]
> South Korea is the name of a country?

Well, but "law" was written uppercase. I can see why you would do that, because there are is a colon after it but I am not sure if that is grammatically correct.

**Comment by Hanro50** [comment]
I feel like we're exploring levels of grammatical correctness that overlooks the scope of the project. This being considered. 

Just remind me at a later date to update the internal translations. Since the English lexipack is more of an example.

**Comment by kz-n** [comment]
I figured it looked a bit nicer with law being uppercase

**Comment by Matix-Media** [comment]
alr

**Pull request merged**
